# -*- coding: utf-8 -*-
"""student_sleep_pattern.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UdfdkB-LCoyJ4HJ7s1YgyDd728unVJLU
"""

# Install fuzzy package
!pip install -U scikit-fuzzy

import numpy as np
import pandas as pd
import skfuzzy as fuzz
from skfuzzy import control as ctrl

# Load dataset
data = pd.read_csv('student_sleep_patterns 2.csv')

# Get dataset columns
data.columns

# Get dataset info
data.info()

# Print value from dataset
print(data)

# Get info about dataset
data.describe(include='all')

# Drop duplicates from dataset
data.drop_duplicates()

# Check whether the dataset contains null value
data.isnull().sum()

# Find max value
data.max()

# Find min value
data.min()


# Rename columns for consistency with code
column_mapping = {
    'Sleep_Duration': 'sleep_duration',
    'Study_Hours': 'study_hours',
    'Screen_Time': 'screen_time',
    'Caffeine_Intake': 'caffeine_intake',
    'Physical_Activity': 'physical_activity',
    'Sleep_Quality': 'sleep_quality',
    'Weekday_Sleep_Start': 'weekday_sleep_start',
    'Weekend_Sleep_Start': 'weekend_sleep_start',
    'Weekday_Sleep_End': 'weekday_sleep_end',
    'Weekend_Sleep_End': 'weekend_sleep_end'
}
data.rename(columns=column_mapping, inplace=True)

# Define fuzzy variables
sleep_duration = ctrl.Antecedent(np.arange(0, 11, 1), 'sleep_duration')
study_hours = ctrl.Antecedent(np.arange(0, 11, 1), 'study_hours')
screen_time = ctrl.Antecedent(np.arange(0, 11, 1), 'screen_time')
caffeine_intake = ctrl.Antecedent(np.arange(0, 11, 1), 'caffeine_intake')
physical_activity = ctrl.Antecedent(np.arange(0, 11, 1), 'physical_activity')
weekday_sleep_start = ctrl.Antecedent(np.arange(0, 11, 1), 'weekday_sleep_start')
weekend_sleep_start = ctrl.Antecedent(np.arange(0, 11, 1), 'weekend_sleep_start')
weekday_sleep_end = ctrl.Antecedent(np.arange(0, 11, 1), 'weekday_sleep_end')
weekend_sleep_end = ctrl.Antecedent(np.arange(0, 11, 1), 'weekend_sleep_end')
sleep_quality = ctrl.Consequent(np.arange(0, 11, 1), 'sleep_quality')

# Define membership functions for all variables
# Membership functions for sleep_duration
sleep_duration['low'] = fuzz.trapmf(sleep_duration.universe, [0, 0, 3, 5])
sleep_duration['medium'] = fuzz.trimf(sleep_duration.universe, [4, 6, 8])
sleep_duration['high'] = fuzz.trapmf(sleep_duration.universe, [7, 9, 10, 10])
sleep_duration.view()

# Membership functions for study_hours
study_hours['low'] = fuzz.trapmf(study_hours.universe, [0, 0, 3, 5])
study_hours['medium'] = fuzz.trimf(study_hours.universe, [4, 6, 8])
study_hours['high'] = fuzz.trapmf(study_hours.universe, [7, 9, 10, 10])
study_hours.view()

# Membership functions for screen_time
screen_time['low'] = fuzz.trapmf(screen_time.universe, [0, 0, 3, 5])
screen_time['medium'] = fuzz.trimf(screen_time.universe, [4, 6, 8])
screen_time['high'] = fuzz.trapmf(screen_time.universe, [7, 9, 10, 10])
screen_time.view()

# Membership functions for caffeine_intake
caffeine_intake['low'] = fuzz.trapmf(caffeine_intake.universe, [0, 0, 2, 4])
caffeine_intake['medium'] = fuzz.trimf(caffeine_intake.universe, [3, 5, 7])
caffeine_intake['high'] = fuzz.trapmf(caffeine_intake.universe, [6, 8, 10, 10])
caffeine_intake.view()

# Membership functions for physical_activity
physical_activity['low'] = fuzz.trapmf(physical_activity.universe, [0, 0, 2, 4])
physical_activity['medium'] = fuzz.trimf(physical_activity.universe, [3, 5, 7])
physical_activity['high'] = fuzz.trapmf(physical_activity.universe, [6, 8, 10, 10])
physical_activity.view()

# Membership functions for weekday_sleep_start
weekday_sleep_start['low'] = fuzz.trapmf(weekday_sleep_start.universe, [0, 0, 2, 4])
weekday_sleep_start['medium'] = fuzz.trimf(weekday_sleep_start.universe, [3, 5, 7])
weekday_sleep_start['high'] = fuzz.trapmf(weekday_sleep_start.universe, [6, 8, 10, 10])
weekday_sleep_start.view()

# Membership functions for weekend_sleep_start
weekend_sleep_start['low'] = fuzz.trapmf(weekend_sleep_start.universe, [0, 0, 2, 4])
weekend_sleep_start['medium'] = fuzz.trimf(weekend_sleep_start.universe, [3, 5, 7])
weekend_sleep_start['high'] = fuzz.trapmf(weekend_sleep_start.universe, [6, 8, 10, 10])
weekend_sleep_start.view()

# Membership functions for weekday_sleep_end
weekday_sleep_end['low'] = fuzz.trapmf(weekday_sleep_end.universe, [0, 0, 2, 4])
weekday_sleep_end['medium'] = fuzz.trimf(weekday_sleep_end.universe, [3, 5, 7])
weekday_sleep_end['high'] = fuzz.trapmf(weekday_sleep_end.universe, [6, 8, 10, 10])
weekday_sleep_end.view()

# Membership functions for weekend_sleep_end
weekend_sleep_end['low'] = fuzz.trapmf(weekend_sleep_end.universe, [0, 0, 2, 4])
weekend_sleep_end['medium'] = fuzz.trimf(weekend_sleep_end.universe, [3, 5, 7])
weekend_sleep_end['high'] = fuzz.trapmf(weekend_sleep_end.universe, [6, 8, 10, 10])
weekend_sleep_end.view()

# Membership functions for sleep_quality
sleep_quality['poor'] = fuzz.trapmf(sleep_quality.universe, [0, 0, 2, 4])
sleep_quality['average'] = fuzz.trimf(sleep_quality.universe, [3, 5, 7])
sleep_quality['good'] = fuzz.trapmf(sleep_quality.universe, [6, 8, 10, 10])
sleep_quality.view()

# Define fuzzy logic rules
rule1 = ctrl.Rule(sleep_duration['low'] | caffeine_intake['high'], sleep_quality['poor'])
rule2 = ctrl.Rule(sleep_duration['medium'] & caffeine_intake['low'], sleep_quality['good'])
rule3 = ctrl.Rule(screen_time['low'], sleep_quality['poor'])
rule4 = ctrl.Rule(physical_activity['high'], sleep_quality['good'])
rule5 = ctrl.Rule(weekday_sleep_start['medium'], sleep_quality['average'])
rule6 = ctrl.Rule(study_hours['high'], sleep_quality['poor'])
rule7 = ctrl.Rule(weekend_sleep_start['low'], sleep_quality['average'])
rule8 = ctrl.Rule(weekend_sleep_end['high'], sleep_quality['good'])
rule9 = ctrl.Rule(weekday_sleep_end['low'], sleep_quality['poor'])
rule10 = ctrl.Rule(physical_activity['medium'], sleep_quality['average'])

# Create control system
sleep_quality_ctrl = ctrl.ControlSystem([rule1, rule2, rule3, rule4, rule5, rule6, rule7, rule8, rule9, rule10])
sleep_quality_sim = ctrl.ControlSystemSimulation(sleep_quality_ctrl)

# Calculate classification result and accuracy
correct_predictions = 0
results = []

total_rows = len(data)

for i in range(total_rows):
    sleep_quality_sim.input['sleep_duration'] = data.loc[i, 'sleep_duration']
    sleep_quality_sim.input['study_hours'] = data.loc[i, 'study_hours']
    sleep_quality_sim.input['screen_time'] = data.loc[i, 'screen_time']
    sleep_quality_sim.input['caffeine_intake'] = data.loc[i, 'caffeine_intake']
    sleep_quality_sim.input['physical_activity'] = data.loc[i, 'physical_activity']
    sleep_quality_sim.input['weekday_sleep_start'] = data.loc[i, 'weekday_sleep_start']
    sleep_quality_sim.input['weekend_sleep_start'] = data.loc[i, 'weekend_sleep_start']
    sleep_quality_sim.input['weekday_sleep_end'] = data.loc[i, 'weekday_sleep_end']
    sleep_quality_sim.input['weekend_sleep_end'] = data.loc[i, 'weekend_sleep_end']

    sleep_quality_sim.compute()
    predicted_sleep_quality = sleep_quality_sim.output['sleep_quality']
    actual_sleep_quality = data.loc[i, 'sleep_quality']

    if ((predicted_sleep_quality >= 5.1 and actual_sleep_quality >= 5) or
        (predicted_sleep_quality < 5.1 and actual_sleep_quality < 5)):
        correct_predictions += 1
        result = "✔"
    else:
        result = "❌"

    print(f"{i+1:<3} {predicted_sleep_quality:.6f} {actual_sleep_quality} {result}")
    results.append([i+1, predicted_sleep_quality, actual_sleep_quality, result])

# Calculate accuracy
accuracy = (correct_predictions / total_rows) * 100
print("\nCorrect Predictions:", correct_predictions, "/", total_rows)
print("Accuracy:", accuracy, "%")

# Save results to CSV
results_df = pd.DataFrame(results, columns=["Index", "Predicted Sleep Quality", "Actual Sleep Quality", "Result"])
results_df.to_csv("sleep_quality_predictions.csv", index=False)

# Verify saved CSV
pd.read_csv("sleep_quality_predictions.csv")

from google.colab import drive
drive.mount('/content/drive')